[package]
name = "shortscale"
version = "0.1.0"
authors = ["Jurgen Leschner <jldec@ciaosoft.com>"]
edition = "2018"
license = "MIT"
description = "Convert numbers into English words using the short scale."

[dependencies]
